### ISSUE TITLE
event binding doesn't work for v-btn / v-btn-link

### ISSUE THREAD

**Issue by lukaszb** [johnleider/vue-materials#22] opened 2016-10-30 13:53 UTC
Basically my method is not called for some reason. I have only just started with vuejs so might be missing something simple.

Anyway, here is a snippet:

``` html
<v-btn @click="foobar()">Foobar</v-btn>
```

However, if I attach event handler to the inner element it works (but not as expected - due to buttons padding user would need to click in on the inner element itself)

``` html
<v-btn><span @click="foobar()">Foobar</span></v-btn>
```

**Comment by johnleider** [comment] 2016-11-01 13:03
Duplicate of [Issue #20](https://github.com/johnleider/vue-materials/issues/20)

**Closed by johnleider** 2016-11-01 13:03 UTC
