### ISSUE TITLE
Build rc5 break v-checkbox component

### ISSUE THREAD

**Issue by cristianstenico** [johnleider/vue-materials#28] opened 2016-11-23 11:01 UTC
Last build broke the v-checkbox component, now I see a text input.
I looked at the html and actually the component does not have the "type" attribute.
In the minified code I noticed that now that attribute is defined in the "staticAttrs" variable, while in the previous builds it was defined in "attrs".
Maybe is there something wrong with webpack configuration (or maybe I'm missing something)?

**Comment by johnleider** [comment] 2016-11-27 05:09
This may be something with your build process. Could you please post it? As well, what vue version are you on?

**Comment by zhanghaowx** [comment] 2016-12-01 05:18
Same with me after upgrade from rc4 => rc5

**Comment by johnleider** [comment] 2016-12-02 01:40
I need some additional information. Could you please post the contents of:

package.json
your webpack config

Also, please post the markup you are using. I cannot reproduce this bug on vue@2.1.3 and vue-materials@1.0.3-rc.5.

**Comment by zhanghaowx** [comment] 2016-12-02 05:28
The same code
```
<v-checkbox v-bind:name="layer.name" v-bind:id="layer.name" v-model="layer.visible">
    {{ layer.name }}
</v-checkbox>
```
works fine in 1.0.3-rc.4 but doesn't work in 1.0.3-rc.5. And that's only I made.

By checking the generated HTML
```
<div class="input-field">
    <p>
        <input id="Terrain" name="Terrain" class="" checked="true" type="checkbox">
        <label for="Terrain">Terrain</label>
    </p>
</div>
```

`type="checkbox"` was seen in 1.0.3-rc.4 but missing in 1.0.3-rc.5

Hope that helps.

**Comment by johnleider** [comment] 2016-12-02 13:14
I'm a bit dumbfounded here. Just installed a new project, added vue-materials, cannot reproduce. The [checkbox ](https://github.com/johnleider/vue-materials/blob/master/src/components/checkbox.vue) component has not changed for 5 months and has the type set to checkbox. RC5 only had one change that was not related to the checkbox in anyway. Is there a way you could provide a jsfiddle or repository that I can clone that demonstrates this bug?

**Comment by cristianstenico** [comment] 2016-12-02 13:33
I think the problem was in your minification process.
If you look at the minified file in rc5, you can find this code:
`("input",{ref:"checkbox","class":classes,attrs:{id:id,name:name,disabled:disabled},staticAttrs:{type:"checkbox"}})`
while in rc4 (and in rc6) the code is different:
`("input",{ref:"checkbox",class:e.classes,attrs:{type:"checkbox",id:e.id,name:e.name,disabled:e.disabled}})`
I don't know exactly why if the "type" attribute moves from attrs to staticAttrs it does not appear in the actual HTML.
(btw, I just tried rc6 and now everything seem to work correctly again)

**Comment by johnleider** [comment] 2016-12-02 14:00
Okay, that makes sense. I'll wait for @zhanghaowx to respond and then I'll close this ticket.

**Comment by zhanghaowx** [comment] 2016-12-02 17:00
@johnleider  The latest version (1.0.5-rc.6) works fine now.

**Comment by johnleider** [comment] 2016-12-02 17:01
Thank you for your help.

**Closed by johnleider** 2016-12-02 17:01 UTC
Labels: bug
